[
{"id":null,"parent_id":null,"created":"\/Date(1632407789062)\/","ws_group":"GetBusinessPartner","action":"FacturarPedido","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  Unable to cast object of type \\u0027RestSharp.RestResponse\\u0027 to type \\u0027Novitec.Mupet.Common.NVTResult\\u0027.\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  Unable to cast object of type \u0027RestSharp.RestResponse\u0027 to type \u0027Novitec.Mupet.Common.NVTResult\u0027. ---\u003e System.InvalidCastException: Unable to cast object of type \u0027RestSharp.RestResponse\u0027 to type \u0027Novitec.Mupet.Common.NVTResult\u0027.\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass3_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 170\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632407997327)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632408999525)\/","ws_group":"GetBusinessPartner","action":"FacturarPedido","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  Unable to cast object of type \\u0027RestSharp.RestResponse\\u0027 to type \\u0027Novitec.Mupet.Common.NVTResult\\u0027.\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  Unable to cast object of type \u0027RestSharp.RestResponse\u0027 to type \u0027Novitec.Mupet.Common.NVTResult\u0027. ---\u003e System.InvalidCastException: Unable to cast object of type \u0027RestSharp.RestResponse\u0027 to type \u0027Novitec.Mupet.Common.NVTResult\u0027.\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass3_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 172\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632409063476)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632409721763)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":null}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"","thirdparty_hook":"","status":"E","finished":"\/Date(1632409788691)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632410030699)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"CATANIA\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"","thirdparty_hook":"","status":"E","finished":"\/Date(1632410075285)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632410747241)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"VATId\":null,\"BPName\":null,\"Group\":0,\"Branch\":null,\"Reason\":null,\"Currency\":\"EUR\",\"PaymentTerms\":0,\"PriceList\":0,\"SurgeonName\":null,\"AddressName1\":null,\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"VATId\":null,\"BPName\":null,\"Group\":0,\"Branch\":null,\"Reason\":null,\"Currency\":\"EUR\",\"PaymentTerms\":0,\"PriceList\":0,\"SurgeonName\":null,\"AddressName1\":null,\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632410793886)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632412435480)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"Branch\":null,\"Reason\":null,\"Currency\":\"EUR\",\"PaymentTerms\":0,\"PriceList\":0,\"SurgeonName\":null,\"AddressName1\":null,\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"Branch\":null,\"Reason\":null,\"Currency\":\"EUR\",\"PaymentTerms\":0,\"PriceList\":0,\"SurgeonName\":null,\"AddressName1\":null,\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632412470742)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632422389704)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632422429232)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632424186118)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632424221217)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632435281095)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"AddressName\":null,\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"AddressName\":null,\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632435307454)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632436067442)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"BPAddresses\":[{\"U_SurgeonAfiliation\":null,\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null},{\"U_SurgeonAfiliation\":null,\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null}],\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"BPAddresses\":[{\"U_SurgeonAfiliation\":null,\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null},{\"U_SurgeonAfiliation\":null,\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null}],\"Country\":\"IT\",\"AddressName2\":null,\"City2\":null,\"ZipCode2\":null,\"AddressLine2\":null,\"Country2\":null}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632436094711)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632436724257)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{},{}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{},{}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632436750766)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632436933201)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632436959443)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632437511005)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632437581972)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632438190439)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002xxx\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  La sesion ha expirado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"CPU00002xxx\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  La sesion ha expirado ---\u003e System.Exception: La sesion ha expirado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 147\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 115\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 87\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 157\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632438234822)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632438597462)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002xxx\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  La sesion ha expirado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"CPU00002xxx\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  La sesion ha expirado ---\u003e System.Exception: La sesion ha expirado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 147\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 115\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 87\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 157\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632438657733)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632438700756)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002xxx\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  La sesion ha expirado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"CPU00002xxx\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  La sesion ha expirado ---\u003e System.Exception: La sesion ha expirado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 147\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 115\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 87\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 157\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632438796109)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632438827177)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  La sesion ha expirado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  La sesion ha expirado ---\u003e System.Exception: La sesion ha expirado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 147\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 115\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 87\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 157\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632438834520)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632438855692)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  La sesion ha expirado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  La sesion ha expirado ---\u003e System.Exception: La sesion ha expirado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 147\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 115\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 87\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 157\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632438864246)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632438963593)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  La sesion ha expirado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  La sesion ha expirado ---\u003e System.Exception: La sesion ha expirado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 147\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 115\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 87\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 157\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632439069732)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
