[
{"id":null,"parent_id":null,"created":"\/Date(1632755728082)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632755754425)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632756032427)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632756056828)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632756174028)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632756200133)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632757529252)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632757554091)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632757795710)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632757821275)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632758144348)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"AddressLine\":null,\"SalesEmployee\":null,\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632758168710)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632770099328)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"AAA00002\"}","old_input":null,"output":"{\"success\":false,\"error\":\"NVTException 5004:  No encontrado\",\"sapHook\":{\"oBusinessPartner\":null},\"thirdPartyHook\":\"AAA00002\"}","nvt_code":5004,"nvt_message":"NVTException 5004: Novitec.Mupet.Common.NVTException:  No encontrado ---\u003e System.Exception: No encontrado\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerStatus(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 177\r\n   at MupetJoy.Security.ClienteRestBLSAP.LeerGet(IRestResponse response) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 135\r\n   at MupetJoy.Security.ClienteRestBLSAP.EjecutarGet(String link) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Security\\ClienteRestBLSAP.cs:line 107\r\n   at MupetJoy.Controllers.BusinessPartnerController.\u003c\u003ec__DisplayClass2_0.\u003cGetBusinessPartner\u003eb__0(SimpleProcess scenario) in Y:\\ProyectosGIT\\EstablishmentLabs\\MupetJoy\\MupetJoy\\Controllers\\BusinessPartnerController.cs:line 136\r\n   at Novitec.Mupet.Scenarios.SimpleProcess.ProcessBody()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.\u003c\u003ec__DisplayClass48_0.\u003cFinish\u003eb__0()\r\n   at Novitec.Mupet.Scenarios.Scenario`1.ProcessCatchable(Action action)\r\n   --- End of inner exception stack trace ---","sap_code":null,"sap_message":null,"sap_hook":null,"thirdparty_hook":null,"status":"E","finished":"\/Date(1632770128016)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632771703644)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632771727464)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
{"id":null,"parent_id":null,"created":"\/Date(1632773310860)\/","ws_group":"GetBusinessPartner","action":"Get Business Partner","visual_aid_label":null,"visual_aid_value":null,"input":"{\"CardCode\":\"CPU00002\"}","old_input":null,"output":"{\"success\":true,\"sapHook\":{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"}]}},\"thirdPartyHook\":\"CPU00002\"}","nvt_code":null,"nvt_message":null,"sap_code":null,"sap_message":null,"sap_hook":"{\"oBusinessPartner\":{\"CardCode\":\"CPU00002\",\"VatIDNum\":null,\"CardName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"CardType\":\"cCustomer\",\"Address\":\"PIAZZA MANCINI BATTAGLIA 5\",\"ContactPerson\":\"Giuseppe Bonadonna\",\"EmailAddress\":\"ua@istitutoclinicovidimura.it\",\"Phone1\":\"095408111\",\"GroupCode\":104,\"U_Branch\":\"IT\",\"U_ReasonCustomer\":null,\"Currency\":\"EUR\",\"U_PaymentTerms\":null,\"PriceListNum\":1,\"U_SurgeonAfiliation\":null,\"BPAddresses\":[{\"AddressType\":\"bo_BillTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"},{\"AddressType\":\"bo_ShipTo\",\"AddressName\":\"ISTITUTO CLINICO VIDIMURA Srl\",\"City\":\"CATANIA\",\"ZipCode\":\"95126\",\"Country\":\"IT\"}]}}","thirdparty_hook":"CPU00002","status":"S","finished":"\/Date(1632773335974)\/","log_error":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsertIdentity(String query, Dictionary`2 parameters, String idColumn)\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteInsert(Query query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.StartLogEntry(Nullable`1 parentId)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20\r\nSystem.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---\u003e System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal\u0026 connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Novitec.Mupet.SAP.DBAccessSAP..ctor()\r\n   at Novitec.Mupet.Common.DBAccess.ExecuteNonQuery(String query, Dictionary`2 parameters)\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntryDB()\r\n   at Novitec.Mupet.Common.LogEntryModel.EndLogEntry(String output, String status, NVTException nvtException, SAPException sapException)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20"},
